Repository SpongePowered/SpongeForge, pull requests merged in 2020-06, with the labels that each got.

#3168 Improve event listener unregistration
  src/main/java/org/spongepowered/mod/mixin/core/fml/common/eventhandler/EventBusMixin_Forge.java
Labels: system: event, type: enhancement

#3166 Nuke McTester
  .travis.yml
  build.gradle
  gradle.properties
  scripts/run-xvfb
  scripts/upload
  src/integration-test/java/org/spongepowered/mod/test/integration/ChatTest.java
  src/integration-test/java/org/spongepowered/mod/test/integration/CreeperTest.java
  src/integration-test/java/org/spongepowered/mod/test/integration/InventoryTest.java
  src/integration-test/java/org/spongepowered/mod/test/integration/UseItemStackTest.java
  src/integration-test/java/org/spongepowered/mod/test/integration/regression/BreakBlockUsedItem.java
  src/integration-test/java/org/spongepowered/mod/test/integration/regression/CrossDimensionCommandBlock.java
  src/integration-test/java/org/spongepowered/mod/test/integration/regression/CustomItemDropTest.java
  src/integration-test/java/org/spongepowered/mod/test/integration/regression/CustomTileRegistration.java
  src/integration-test/java/org/spongepowered/mod/test/integration/regression/FlowerPotDropTest.java
  src/integration-test/java/org/spongepowered/mod/test/integration/regression/TntExplosionTest.java
  src/integration-test/java/org/spongepowered/mod/test/integration/regression/UseItemStackFinishBug.java
  src/integration-test/java/org/spongepowered/mod/test/integration/regression/schematic/PlacingSchematicTest.java
  src/integration-test/kotlin/org/spongepowered/mod/CreeperTestKotlin.kt
  src/integration-test/resources/placement.schematic
Labels: version: 1.12

#3176 Add ChunkEvent.Unload to forgeToSpongeEventMapping
  src/main/java/org/spongepowered/mod/event/SpongeModEventManager.java
Labels: status: accepted, system: event

#3177 Move entity death logging to common and remove internal listener for LivingDeathEvent
  src/main/java/org/spongepowered/mod/SpongeMod.java
Labels: system: event, type: bug

#3131 Fix missing ShouldFires
  src/main/java/org/spongepowered/mod/mixin/core/block/BlockFireMixin_Forge.java
  src/main/java/org/spongepowered/mod/mixin/core/block/BlockLeavesMixin_Forge.java
  src/main/java/org/spongepowered/mod/mixin/core/block/BlockLogMixin_Forge.java
  src/main/java/org/spongepowered/mod/mixin/core/forge/common/ForgeHooksMixin_Forge.java
  src/main/java/org/spongepowered/mod/mixin/core/forge/fluids/BlockFluidBaseMixin_Forge.java
  src/main/java/org/spongepowered/mod/mixin/core/forge/fluids/BlockFluidFiniteMixin_Forge.java
  src/main/java/org/spongepowered/mod/mixin/core/world/WorldServerMixin_Forge.java
Labels: system: event, type: performance
